//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_t
    {
        public int Id { get; set; }
        public System.Guid Uid { get; set; }
        public string Cron { get; set; }
        public System.Guid ApplicationUid { get; set; }
        public string Paras { get; set; }
        public int Enable { get; set; }
        public int LogWhen { get; set; }
        public string LogPattern { get; set; }
        public string LogPath { get; set; }
        public string Memo { get; set; }
        public int Repeat { get; set; }
        public Nullable<int> Delay { get; set; }
    }
}
