//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSystemManageWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_t
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public Nullable<System.Guid> ScheduleUid { get; set; }
        public int Result { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
    }
}
